# -*- coding: utf-8 -*-
"""Mini_project_ml_v3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dlSBhbgDppDxBSW-0bBCaUiQVpRGP5cH
"""

# -*- coding: utf-8 -*-
print("[PROGRESS] Starting Phase 1: Environment Setup...")

import os
os.system("pip install -q gradio")

import numpy as np
import scipy.signal as signal
from sklearn.neural_network import MLPRegressor
import matplotlib.pyplot as plt
import gradio as gr
import time

print("[STATUS] Libraries imported successfully.")
print("[SUCCESS] Phase 1 Complete!\n")

print("[PROGRESS] Starting Phase 2: Plant Modelling...")

R = 0.4
L = 0.1
J = 0.02
b = 0.01
K = 0.15

num = [K]
den = [J*L, (J*R + b*L), (b*R + K**2)]

A_c, B_c, C_c, D_c = signal.tf2ss(num, den)
dt = 0.05
sys_disc = signal.cont2discrete((A_c, B_c, C_c, D_c), dt, method='bilinear')
A_d, B_d, C_d, D_d = sys_disc[0], sys_disc[1], sys_disc[2], sys_disc[3]

time_steps = 100
print("[SUCCESS] Phase 2 Complete!\n")

print("[PROGRESS] Starting Phase 3: Generating training data...")

X_train, Y_train = [], []
Kp, Ki, Kd = 2.5, 0.8, 0.1
training_setpoints = [10, 20, 30, 40, 50, 60]

for target in training_setpoints:
    x_state = np.zeros((2, 1))
    speed = 0.0
    prev_error = target
    integral = 0.0

    for t in range(time_steps):
        error = target - speed
        integral += error * dt
        derivative = (error - prev_error) / dt

        u = (Kp * error) + (Ki * integral) + (Kd * derivative)
        u = np.clip(u, -24, 24)

        X_train.append([error, integral, derivative])
        Y_train.append(u)

        x_state = np.dot(A_d, x_state) + np.dot(B_d, np.array([[u]]))
        speed = float(np.dot(C_d, x_state))
        prev_error = error

X_train, Y_train = np.array(X_train), np.array(Y_train)
print("[SUCCESS] Phase 3 Complete!\n")

print("[PROGRESS] Starting Phase 4: Training Neural Network...")

mlp_controller = MLPRegressor(
    hidden_layer_sizes=(64, 32),
    activation='relu',
    max_iter=3000,
    random_state=42,
    solver='adam'
)

mlp_controller.fit(X_train, Y_train)
print(f"[STATUS] Network trained. Final loss: {mlp_controller.loss_:.6f}")
print("[SUCCESS] Phase 4 Complete!\n")

print("[PROGRESS] Starting Phase 5: Launching GUI Terminal...")
def evaluate_and_compare(target_setpoint, enable_noise, noise_level, enable_disturbance, disturbance_time):
    t_arr = np.arange(0, time_steps * dt, dt)
    np.random.seed(42)

    # Avoid mathematical division by zero if target is set exactly to 0
    test_target = target_setpoint if target_setpoint != 0 else 1e-5

    noise = np.random.normal(0, noise_level, time_steps) if enable_noise else np.zeros(time_steps)

    # --- 1. Classical PID Loop ---
    pid_speeds = []
    x_state = np.zeros((2, 1))
    speed = 0.0
    prev_error = target_setpoint
    integral = 0.0
    for t in range(time_steps):
        pid_speeds.append(speed)
        measured_speed = speed + noise[t]
        error = target_setpoint - measured_speed
        integral += error * dt
        derivative = (error - prev_error) / dt
        u = np.clip((Kp * error) + (Ki * integral) + (Kd * derivative), -24, 24)
        dist_voltage = -8.0 if (enable_disturbance and (t * dt) >= disturbance_time) else 0.0
        total_u = np.clip(u + dist_voltage, -24, 24)
        x_state = np.dot(A_d, x_state) + np.dot(B_d, np.array([[total_u]]))
        speed = float(np.dot(C_d, x_state) + np.dot(D_d, np.array([[total_u]])))
        prev_error = error
    # --- 2. ML ANN Controller ---
    ann_speeds = []
    x_state = np.zeros((2, 1))
    speed = 0.0
    prev_error = target_setpoint
    integral = 0.0
    for t in range(time_steps):
        ann_speeds.append(speed)
        measured_speed = speed + noise[t]
        error = target_setpoint - measured_speed
        integral += error * dt
        derivative = (error - prev_error) / dt

        u_pred = mlp_controller.predict([[error, integral, derivative]])[0]
        u_pred = np.clip(u_pred, -24, 24)

        dist_voltage = -8.0 if (enable_disturbance and (t * dt) >= disturbance_time) else 0.0
        total_u = np.clip(u_pred + dist_voltage, -24, 24)

        x_state = np.dot(A_d, x_state) + np.dot(B_d, np.array([[total_u]]))
        speed = float(np.dot(C_d, x_state) + np.dot(D_d, np.array([[total_u]])))
        prev_error = error
    pid_speeds, ann_speeds = np.array(pid_speeds), np.array(ann_speeds)
    # --- 3. Compute Metrics & Fix Missing Table Variables ---
    pid_mse = np.mean((target_setpoint - pid_speeds)**2)
    ann_mse = np.mean((target_setpoint - ann_speeds)**2)

    pid_overshoot = max(0.0, ((np.max(pid_speeds) - test_target) / test_target) * 100)
    ann_overshoot = max(0.0, ((np.max(ann_speeds) - test_target) / test_target) * 100)
    def calculate_transients(speeds, target):
        try:
            t_10 = next(t*dt for t, v in enumerate(speeds) if v >= 0.10 * target)
            t_90 = next(t*dt for t, v in enumerate(speeds) if v >= 0.90 * target)
            rt = t_90 - t_10
            st = 5.0
            for t in reversed(range(len(speeds))):
                if abs(speeds[t] - target) > (0.05 * target):
                    st = (t + 1) * dt
                    break
            return max(0.05, rt), min(5.0, st)
        except:
            return 0.0, 5.0
    pid_rt, pid_st = calculate_transients(pid_speeds, test_target)
    ann_rt, ann_st = calculate_transients(ann_speeds, test_target)
    # Plot
    plt.figure(figsize=(10, 5))
    plt.plot(t_arr, [target_setpoint]*time_steps, 'r--', label='Target Setpoint')
    plt.plot(t_arr, pid_speeds, 'b-', linewidth=2, label=f'Classical PID (MSE: {pid_mse:.2f})')
    plt.plot(t_arr, ann_speeds, 'g-', linewidth=2, label=f'ML ANN Controller (MSE: {ann_mse:.2f})')

    if enable_disturbance:
        plt.axvline(x=disturbance_time, color='orange', linestyle=':', label='Disturbance applied')

    plt.xlabel('Time (Seconds)')
    plt.ylabel('Velocity Dynamics (rad/s)')
    plt.title('PID vs. Machine Learning Performance under Stress')
    plt.legend(loc='lower right')
    plt.grid(True, alpha=0.4)

    plot_path = "stress_test_analysis.png"
    plt.savefig(plot_path, dpi=200, bbox_inches='tight')
    plt.close()

    metrics_markdown = f"""### 📊 Performance Assessment Report

| System Performance Metric | Classical PID Implementation | Machine Learning (ANN) Implementation |
| :--- | :--- | :--- |
| **Mean Squared Error (MSE)** | {pid_mse:.4f} | {ann_mse:.4f} |
| **Peak Overshoot (%)** | {pid_overshoot:.2f}% | {ann_overshoot:.2f}% |
| **Rise Time (seconds)** | {pid_rt:.3f}s | {ann_rt:.3f}s |
| **Settling Time (5% Band)** | {pid_st:.3f}s | {ann_st:.3f}s |

"""
    return plot_path, metrics_markdown
gui_interface = gr.Interface(
    fn=evaluate_and_compare,
    inputs=[
        gr.Slider(minimum=0.0, maximum=100.0, value=30.0, label="Target Speed (rad/s)"),
        gr.Checkbox(label="Enable Sensor Noise", value=False),
        gr.Slider(minimum=0.0, maximum=5.0, value=0.5, step=0.01, label="Noise Amplitude"),
        gr.Checkbox(label="Enable Sudden Physical Load", value=False),
        gr.Slider(minimum=0.0, maximum=5.0, value=2.0, step=0.01, label="Load Hit Time (Seconds)")
    ],
    outputs=[gr.Image(type="filepath", label="Control Trajectories"), gr.Markdown()],
    title="Control Systems Evaluation Terminal",
    description="Compare Classical PID Loops vs. Supervised Neural Network Controllers under noise and physics disturbances.",
    theme="soft"
)
if __name__ == "__main__":
    gui_interface.launch(share=True, debug=False)